# Generated by Django 5.0.2 on 2024-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_fleets_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleets',
            old_name='license_no',
            new_name='registration_no',
        ),
        migrations.AddField(
            model_name='fleets',
            name='token_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
