# Generated by Django 5.0.2 on 2024-02-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_license_no_fleets_registration_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleets',
            name='password',
        ),
    ]
